apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: translator-fr-en
  namespace: christian
  labels:
    app: seldon
spec:
  predictors:
    - componentSpecs:
      - spec:
          containers:
          - name: translator-baseline
            image: chritter/translator:0.5
            imagePullPolicy: IfNotPresent
          - image: chritter/translator:0.5
            name: translator-new
            imagePullPolicy: IfNotPresent
          terminationGracePeriodSeconds: 20
      graph:
        name: translator-abtest
        implementation: RANDOM_ABTEST
        parameters:
        - name: ratioA
          value: '0.7'
          type: FLOAT
        children:
        - name: translator-baseline
          type: MODEL
          children: []
        - name: translator-new
          type: MODEL
          children: []
      name: main
      replicas: 1