apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: translator-fr-en
  namespace: christian
  labels:
    app: seldon
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: translator-baseline
          image: chritter/translator:0.5
          imagePullPolicy: IfNotPresent
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: translator-baseline
      type: MODEL
    name: main
    replicas: 1
    traffic: 50
  - componentSpecs:
    - spec:
        containers:
        - name: translator-new
          image: chritter/translator:0.5
          imagePullPolicy: IfNotPresent
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: canary
    replicas: 1
    traffic: 50
