apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: XSvjC1xZm0BjRInC2HQf
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: 4wvOUGhym11GdOo1FVKGxbEFJdBNrs4MzbK8Rpor
  RCLONE_CONFIG_S3_ENDPOINT: http://minio-1631912584.minio.svc.cluster.local:9000
