apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-abtest
spec:
  name: seldon-abtest
  predictors:
  - name: default
    replicas: 1
    componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier:1.11.0-dev
          imagePullPolicy: IfNotPresent
          name: classifier-1
          resources:
            requests:
              memory: 1Mi
        - image: seldonio/mock_classifier:1.11.0-dev
          imagePullPolicy: IfNotPresent
          name: classifier-2
          resources:
            requests:
              memory: 1Mi
        terminationGracePeriodSeconds: 20
    graph:
      name: seldon-abtest
      implementation: RANDOM_ABTEST
      parameters:
      - name: ratioA
        value: '0.5'
        type: FLOAT
      children:
      - name: classifier-1
        type: MODEL
        children: []
      - name: classifier-2
        type: MODEL
        children: []