apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: mAfJY6IRUl6gOrW0ztuv
  AWS_SECRET_ACCESS_KEY: J02jiu8XnJT4nNEpL98pn7wc4bF5H8M6pkh1PcQa
  AWS_ENDPOINT_URL: http://minio-1631912584.minio.svc.cluster.local:9000
  S3_ENDPOINT: http://minio-1631912584.minio.svc.cluster.local:9000
  USE_SSL: "false"
