apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: aVym8xoWIiF82mczOgTf
  AWS_SECRET_ACCESS_KEY: 5miISZoZa0aHTwo2aMwdHgu1ALPpjEU2GD9Qvkmq
  AWS_ENDPOINT_URL: http://minio-1631912584.minio.svc.cluster.local:9000
  USE_SSL: "false"
